name: Deploy to Lightsail

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: npm install

    - name: Build Quasar app
      run: |
        npm install -g @quasar/cli
        quasar build

    - name: Setup SSH
      run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 52.197.225.198 >> ~/.ssh/known_hosts

    - name: Deploy via SCP
      run: |
          scp -r dist/spa/* ubuntu@52.197.225.198:/var/www/html/
